"""empty message

Revision ID: 283ea71fbd3b
Revises: da675153b602
Create Date: 2020-01-10 13:36:27.999037

"""

# revision identifiers, used by Alembic.
revision = '283ea71fbd3b'
down_revision = 'da675153b602'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
