"""empty message

Revision ID: da675153b602
Revises: 4f2e2c180af
Create Date: 2020-01-10 13:29:03.400296

"""

# revision identifiers, used by Alembic.
revision = 'da675153b602'
down_revision = '4f2e2c180af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.String(length=300), nullable=False),
    sa.Column('nanodegree_key', sa.String(length=300), nullable=False),
    sa.Column('udacity_user_key', sa.Integer(), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ENROLLED', 'UNENROLLED', name='enrollmentstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollment')
    # ### end Alembic commands ###
