"""empty message

Revision ID: f89021a57486
Revises: feb6f20897ce
Create Date: 2020-01-12 12:19:14.248667

"""

# revision identifiers, used by Alembic.
revision = 'f89021a57486'
down_revision = 'feb6f20897ce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
