"""empty message

Revision ID: feb6f20897ce
Revises: 283ea71fbd3b
Create Date: 2020-01-10 13:44:13.249029

"""

# revision identifiers, used by Alembic.
revision = 'feb6f20897ce'
down_revision = '283ea71fbd3b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enrollment', 'enrollment_id',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enrollment', 'enrollment_id',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    # ### end Alembic commands ###
